spring.application.name=modbus-sbh
logging.level.root=INFO
server.servlet.context-path=/chaos
server.port=10280

#??
scale.serial.portName=COM1

# TBox??
tbox.serial.port.name=COM3
# ?????500ms
tbox.serial.timeout.read=500
# TBOX?????60?
tbox.tbox.init.delay=60000

#modbus-tcp??
modbustcp.host=192.168.1.6
modbustcp.port=502

equip.no=test
point.no=test
kafka.url=192.168.1.252:9092
kafka.topic=shandonghuangjin
#????????????
offline.cache.day=3

# rfid????????
rfid.serial.port.name=COM4

#?????????1??????? 2??GHH??? 3???????
sampling.kuangche.flag=2

