spring.application.name=modbus-sbh
logging.level.root=INFO
server.servlet.context-path=/chaos
server.port=10280

#每5分钟取执行一次
cron.raw-data=0 0/5 * * * ?

#???484?????
#??
scale.serial.portName=COM1

# ???????????HPM??????V1.1?
# ????Windows?COMx?Linux?/dev/ttyUSBx
tbox.serial.port.name=COM3
# ?????500ms?????????????????
tbox.serial.timeout.read=500
# TBOX?????
# TBOX??????60??????????????JSON???
tbox.tbox.init.delay=60000


